---
zabbix_version: "7.0"
postgres_version: 16
postgres_old_version: 14

zabbix_release_deb: "zabbix-release_latest_7.0+debian12_all.deb"
zabbix_release_url: "https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/{{ zabbix_release_deb }}"
